### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by eli-s-r** [knazir/SeePlusPlus#61]
Hi! seepluspl.us has been down for a little bit, are there any plans to bring the site back up and continue to provide access to this amazing tool? Thanks so much!

**Comment by Naereen** [comment]
Still down, @knazir and colleagues, do you think you'll be able to make it work again?

**Comment by knazir** [comment]
Apologies @eli-s-r and @Naeer, I had lost access to the primary email where I received notifications from GitHub for quite a while without realizing it... very silly of me. The site has been restored for the past year or so now, so I'll mark this as closed. Please reach out if you run into any troubles.
